{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pizza Service Logs PROD",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} | json"
    }
   ]
  },
  {
   "title": "Pizza Service Logs DEV",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service-dev\"} | json"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pizza_latency{success=\"true\", source=\"jwt-pizza-service\", metric=\"creation\"}",
     "legendFormat": "Pizza Creation Latency"
    }
   ]
  },
  {
   "title": "Pizzas Sold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pizza_total{metric=\"sold\", source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizzas Sold"
    },
    {
     "expr": "pizza_total{metric=\"creation\", success=\"false\"}",
     "legendFormat": "Failed Pizza Creations"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "endpoint_latency{source=\"jwt-pizza-service\"}",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "users_total{active=\"true\", source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Authentication Requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "60 * rate(auth_total{source=\"jwt-pizza-service\", success=\"true\"}[$__rate_interval])",
     "legendFormat": "Successful"
    },
    {
     "expr": "60 * rate(auth_total{source=\"jwt-pizza-service\", success=\"false\"}[$__rate_interval])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Pizza Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_total{metric=\"revenue\", source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "60 * rate(request_total{method=\"get\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Get Requests"
    },
    {
     "expr": "60 * rate(request_total{method=\"delete\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Delete Requests"
    },
    {
     "expr": "60 * rate(request_total{method=\"post\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Post Requests"
    },
    {
     "expr": "60 * rate(request_total{method=\"put\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Put Requests"
    },
    {
     "expr": "sum(60 * rate(request_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "All Requests"
    }
   ]
  },
  {
   "title": "Sytem Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{metric=\"memory\", source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "system_usage{metric=\"cpu\", source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}